### PR TITLE
Remove unused example

### PR DESCRIPTION
**Pull request by conorbros**
Not sure how this slipped through...

### CODE REVIEW

**Review by rukai — APPROVED** [review]
nice cleanup

**Comment by rukai** [comment]
Oh, I believe I was using this for benchmarking the rate-limiting with examples/cassandra_bench.rs and it accidentally got included in unrelated PR.

Even though it is useful for benchmarking, I think it should still be removed considering it will bitrot without a related integration test.

**Comment by conorbros** [comment]
Ah, makes sense. I actually assumed it was one of mine lol

**Comment by rukai** [comment]
After thinking more, maybe we should just add an integration test to avoid bitrot.
But also in place of that, deleting it is fine.

**Review by benbromhead — APPROVED** [review]

**Pull request merged**
