### PR TITLE
Update to rust 1.60

### PR DESCRIPTION
**Pull request by rukai**
https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html

### CODE REVIEW

**Review by conorbros — APPROVED** [review]

**Comment by rukai** [comment]
I tested that bench locally and it does seem to be giving a ~5-10% regression locally.
While I dont think its worth blocking this PR, it might be worth investigating?
I'm leaning towards not investigating though, rust 1.60 includes an upgrade to LLVM 14 so we probably just got unlucky with the chaotic nature of LLVM optimization.

**Comment by conorbros** [comment]
Curious it's only one benchmark regressing.

**Comment by rukai** [comment]
Its quite likely lots of benchmarks are affected but this was the only one that got combined with enough CI performance variance to tip past the 30% reporting threshold

**Comment by benbromhead** [comment]
Do you want to just confirm the other benchmarks. We can wait till the next rust ver if we are seeing regressions across the board.

**Comment by rukai** [comment]
Running every bench once there is various +-5% results which is easily within expected noise.
So im not seeing any trend up or down.
I think this is fine to merge.

**Review by benbromhead — APPROVED** [review]

**Pull request merged**
