### PR TITLE
Upgrade remaining cassandra int tests to cassandra 4.0.6

### PR DESCRIPTION
**Pull request by rukai**
Update all cassandra 3 integration tests to cassandra 4 (unless we are testing our handling of something cassandra 3 specific)

### CODE REVIEW

**Comment by conorbros** [comment]
Why 4.0.6?

**Comment by rukai** [comment]
oh huh, your right, 4.0.6 is old...
does bitnami not have images for recent releases? https://hub.docker.com/r/bitnami/cassandra/tags

**Comment by conorbros** [comment]
4.0.6 is the latest. Just wondering why we should specify that?

**Comment by rukai** [comment]
Pinning to a specific version sounds like the best idea to me.
Everything else in this project has versions pinned e.g. we have the Cargo.lock checked in protecting us in the case that some crate fails to follow semver or introduces a new bug or fixes a bug we relied on.
I dont see why that should be different for our int test db images.

If we find issues with 4.0.6 or we just want to make sure shotover continues to function on the latest release, we can always upgrade to a later version manually.

**Review by conorbros — APPROVED** [review]

**Review by benbromhead — APPROVED** [review]

**Pull request merged**
