### PR TITLE
use check_frame instead of from_buffer

### PR DESCRIPTION
**Pull request by conorbros**
Use a new method that only checks the frame length and version of incoming Cassandra frames before fully parsing them. 

Latte benchmarks against main:
image

<s>Waiting on https://github.com/krojew/cdrs-tokio/pull/93 to be merged.</s>

### CODE REVIEW

**Comment by Claude-at-Instaclustr** [comment]
Are we going to release the cdrs-tokio package ourselves?

**Comment by conorbros** [comment]
No, my changes were just upstreamed.

**Comment by rukai** [comment]
What about the from_buffer calls in metadata and cell_count?

cell_count needs to access the body so not much we can do there.

But maybe for metadata we need a method that only reads the header?
Should that be combined with the check_frame_size method?
Do we care about the performance of metadata in the first place?

**Comment by conorbros** [comment]
Yeah, we can definitely speed that up too. Although it's in a much less hot path than this so I would prefer to get this merged first and investigate later.

**Review by rukai — APPROVED** [review]
Given that you've already landed `check_frame_size` in cassandra-protocol, I agree completely lets just land this.

If we were still running off a cassandra-protocol fork I would have pushed for more experimentation in the cassandra-protocol API before trying to upstream it to reduce upstream churn.

This is fine though.
Very nice win.

**Review by XA21X — APPROVED** [review]

**Pull request merged**
