### PR TITLE
Move rdkafka back to crates.io

### PR DESCRIPTION
**Pull request by rukai**
We previously had to use git here due to a bug in the driver, now the new version has been released we can go back to proper versioning.

### CODE REVIEW

**Comment by rukai** [comment]
will investigate failure

**Comment by rukai** [comment]
The cause is the same as the original issue that caused us to switch to the git dep in https://github.com/shotover/shotover-proxy/pull/1228

Current theory why this happened:

The branch that we depended on never made it to main, instead a different PR to upgrade the underlying C library was merged. Maybe there was some extra changes in that branch that fixed the issue somehow.
Maybe its some spooky UB issue caused by slight change in compilation.

**Comment by rukai** [comment]
I was never able to fully understand what the issue is in the rdkafka driver, but I was able to fix the issue by ensuring that shotover never returned duplicate addresses in its list of brokers.

It feels a bit unfortunate that we need to perform deduplication as it adds a bunch of complexity.
The drivers should probably be able to handle this case, but its also not something that kafka itself would ever do so it seems unreasonable to request that they do handle it.
Additionally say if we fixed it in the C driver similar issues could appear in other drivers.

**Review by conorbros — APPROVED** [review]

**Review by cjrolo — APPROVED** [review]
Is this MetadataResponse structure small? Otherwise we might iterate over a large object several times.

**Comment by rukai** [comment]
I assume you mean MetadataResponseBroker? It looks like this:
image

Looking at this with fresh eyes though, I think using MetadataResponseBroker is wrong because we dont want to include other fields in the comparison, I'll replace it with KafkaAddress.

**Pull request merged**
