### PR TITLE
Remove topics & Mpsc source

### PR DESCRIPTION
**Pull request by conorbros**
This change removes the concept of topics and the Mpsc source because: 
- Topics are only passed through chains to be passed to any subchains that are created and so on.
- We have no tests or indication of how the Mpsc source is supposed to be used.

I also moved `ChannelMessage` to `chain.rs` and named it more appropriately.

### CODE REVIEW

**Comment by rukai** [comment]
"I also moved ChannelMessage to chain.rs and named it more appropriately."
Can this go in a separate PR so we can consider the removal of topics separately?

**Comment by conorbros** [comment]
I'll revert that commit and open another PR after (if) this one is merged.

**Comment by benbromhead** [comment]
Yup happy to remove this concept.

**Review by benbromhead — APPROVED** [review]

**Review by rukai — APPROVED** [review]
I'm all for removing features that dont have a solid use case and are untested.
The changes look good too.

**Pull request merged**
