### PR TITLE
Rename message::Value

### PR DESCRIPTION
**Pull request by rukai**
I chose ShotoverValue but maybe something like GenericValue or MessageValue could work?

### CODE REVIEW

**Review by conorbros — APPROVED** [review]
I prefer `MessageValue` because I imagine a transform developer interacting with `Message` and `MessageValue` better than `Message` and `ShotoverValue` but isn't a big deal so LGTM.

**Comment by rukai** [comment]
Yeah, after thinking about it, I agree, MessageValue does sound better.
ill swap to that.

**Review by benbromhead — APPROVED** [review]

**Review by benbromhead — COMMENTED** [review]
I'm ok with MessageValue, but something like DatastoreValue is more descriptive (e.g. it is a value from the datastore)

**Comment by rukai** [comment]
It is currently used in cases the value didnt come from a datastore, so atm MessageValue makes more sense.
Although we might want to remove those cases in the future and then DatastoreValue would end up a better name.

**Pull request merged**
