### PR TITLE
Kafka message parsing

### PR DESCRIPTION
**Pull request by conorbros**

### CODE REVIEW

**Review by rukai — APPROVED** [review]
Nice!
Thanks for solving this so we dont have to worry about adding anymore in the future!

**Comment by rukai** [comment]
Woah, looks like this PR increases the size of the binary by 4MB probably still worth it though.

**Comment by rukai** [comment]
Oh, this PR adds 3 minutes release build time in CI, maybe we should at least measure how long a release build takes locally before we merge.

**Review by rukai — CHANGES_REQUESTED** [review]
We should measure effect on release build time locally before merging.
Maybe we can alter the kafka-parser crate to improve build times or maybe removing the use of generics here would help

**Review by cjrolo — APPROVED** [review]

**Review by rukai — APPROVED** [review]
I tested the build time locally.
On my machine, this PR increases the time to run `cargo build --release -p shotover-proxy --no-default-features --features kafka` from 1min 15s to 1min 32s

This is an unfortunate regression, but we do want to be parsing every kafka message, so lets land it and possibly investigate ways to speed it up in the future.

**Pull request merged**
