### PR TITLE
#1656 Split up scram_over_mtls module into submodules

### LINKED ISSUE #1656: splitup the `scram_over_mtls` module.
blocked on https://github.com/shotover/shotover-proxy/pull/1654

Split the `scram_over_mtls` module up to have 2 new submodules:
* `recreate_token_queue` module should include:
  + The `RecreateTokenQueue` struct and its methods
  + The `TokenToRecreate` struct and its methods
* `create_token` module should include:
  + the `create_token_with_timeout` function
  + the `find_new_brokers` function
  + the `create_delegation_token_for_user` function
  + the `wait_until_delegation_token_ready_on_all_brokers` function
  + the `is_delegation_token_ready` function
  
The new file structure will look like:
* `scram_over_mtls.rs`
* `scram_over_mtls/recreate_token_queue.rs`
* `scram_over_mtls/create_token.rs`

Make sure to include:
```rust
mod recreate_token_queue;
mod create_token;
```
in `scram_over_mtls.rs` to import the 2 submodules.

### PR DESCRIPTION
**Pull request by justinweng-instaclustr**
This PR splits up the original monolithic module `scram_over_mtls` into submodules `recreate_token_queue` and `create_token` in order to prepare for the improvement on token handling in https://github.com/shotover/shotover-proxy/issues/1667. It doesn't change the functionality of the module `scram_over_mtls`.

Closes #1656

### CODE REVIEW

**Review by rukai — APPROVED** [review]
I pasted the moved code into a diff tool and can confirm that the code is unchanged, except for a few error message typo fixes.
Nice!

**Comment by justinweng-instaclustr** [comment]
> I pasted the moved code into a diff tool and can confirm that the code is unchanged, except for a few error message typo fixes. Nice!

Thanks for checking! JOOC, what diff tool did you use?

**Review by ronycsdu — APPROVED** [review]

**Comment by rukai** [comment]
> Thanks for checking! JOOC, what diff tool did you use?
Not sure 🤣 
I googled "web diff tool" and picked the first result.

**Comment by rukai** [comment]
From my history it was: https://www.diffchecker.com/

**Pull request merged**
