### PR TITLE
store single cql statement instead of a vec

### PR DESCRIPTION
**Pull request by rukai**
Makes progress towards https://github.com/shotover/shotover-proxy/issues/563
Also makes progress towards using the new cql parser as that will return only a single statement.

A cassandra query can only contain a single statement, the only reason it was a vec here was because that was what the sqlparser crate returned.

### CODE REVIEW

**Comment by conorbros** [comment]
Why is this progress towards #563?

**Comment by rukai** [comment]
ah I guess its not technically progress but ... its an obvious refactor that I spotted while working on https://github.com/shotover/shotover-proxy/pull/570

**Review by conorbros — APPROVED** [review]
Sounds good to me

**Review by benbromhead — APPROVED** [review]
yay!

**Pull request merged**
