### PR TITLE
Fix intermittent redis failure

### PR DESCRIPTION
**Pull request by rukai**
Fixes this intermittent failure I saw on CI and could reproduce locally:
image

Its strange because `CLUSTER NODES` will succeed and then `CLUSTER REPLICAS` will return an empty list.
I imagine the cause is some state specific to `CLUSTER REPLICAS` that redis needs to populate during initialization before `CLUSTER REPLICAS` can return sensible values.

I have run this script for a while:
```bash
set -e
set -u
while :;
do
    cargo test --all-features redis_int_tests::test_cluster_handling_redis;
done
```
And the only failure I could get is another presumably unrelated redis failure: `An error was signalled by the server: The specified node is not a master`

### CODE REVIEW

**Comment by conorbros** [comment]
image

Did you ever get this one?

**Comment by rukai** [comment]
Never, seen that one before, are you getting that locally atm?

**Comment by conorbros** [comment]
Yeah getting that on this branch.

**Review by benbromhead — APPROVED** [review]

**Comment by conorbros** [comment]
Thanks to your new assert messages: 

image

**Comment by rukai** [comment]
Does the failure occur every run or is it intermittent?
And does it occur on main branch as well?

**Comment by conorbros** [comment]
Intermittent, and no I was not able to reproduce on main.

**Review by conorbros — APPROVED** [review]

**Pull request merged**
