### PR TITLE
Use statement integration tests

### PR DESCRIPTION
**Pull request by rukai**
The integration tests in this PR demonstrate some unfortunate realities about use statements: both batches and prepared statements take the `use`d keyspace into account.

This will affect how we go about handling keyspaces when identifying a keyspace/table pair.

### CODE REVIEW

**Comment by rukai** [comment]
`cargo test --all-features test_cluster_multi_rack` fails locally and appears to reveal a bug in shotover

**Comment by rukai** [comment]
To avoid blocking the PR I commented out the bit that fails, we can enable it once we fix the underlying shotover issue, which will require in depth investigation.

**Review by conorbros — APPROVED** [review]
LGTM. Did you open an issue for the problem?

**Comment by rukai** [comment]
done https://github.com/shotover/shotover-proxy/issues/811

**Review by benbromhead — APPROVED** [review]

**Pull request merged**
