### PR TITLE
remove use of feature specific to cassandra-proto fork

### PR DESCRIPTION
**Pull request by rukai**
* Simplifies the implementation
* Removes dependency on feature added in our cassandra-proto fork (in upstream Row.metadata and Row.row_content are private)
* Less allocation

### CODE REVIEW

**Comment by conorbros** [comment]
Are we able to test that function?

**Comment by rukai** [comment]
We already have test_result_codec, which sends a return value decodes and encodes a return value.
That should cover this function.

**Comment by benbromhead** [comment]
Can we remove dependence on our fork altogether or is this just one part.

**Comment by rukai** [comment]
This is just step one on our side. I've also made some PRs for things we need on their side

**Review by benbromhead — APPROVED** [review]

**Review by conorbros — APPROVED** [review]

**Pull request merged**
